export const BADGES = {
  questioner: {
    key: "questioner",
    name: "Questioner",
    tier: "bronze",
    threshold: 1,
    counter: "questions",
  },
  silverQuestioner: {
    key: "silverQuestioner",
    name: "Questioner II",
    tier: "silver",
    threshold: 5,
    counter: "questions",
  },
  goldQuestioner: {
    key: "goldQuestioner",
    name: "Questioner III",
    tier: "gold",
    threshold: 25,
    counter: "questions",
  },
  teacher: {
    key: "teacher",
    name: "Teacher",
    tier: "bronze",
    threshold: 1,
    counter: "answers",
  },
  silverTeacher: {
    key: "silverTeacher",
    name: "Teacher II",
    tier: "silver",
    threshold: 10,
    counter: "answers",
  },
  goldTeacher: {
    key: "goldTeacher",
    name: "Teacher III",
    tier: "gold",
    threshold: 50,
    counter: "answers",
  },
  scholar: {
    key: "scholar",
    name: "Scholar",
    tier: "bronze",
    threshold: 1,
    counter: "acceptedAnswers",
  },
  silverScholar: {
    key: "silverScholar",
    name: "Scholar II",
    tier: "silver",
    threshold: 5,
    counter: "acceptedAnswers",
  },
  goldScholar: {
    key: "goldScholar",
    name: "Scholar III",
    tier: "gold",
    threshold: 25,
    counter: "acceptedAnswers",
  },
  niceQuestion: {
    key: "niceQuestion",
    name: "Nice Question",
    tier: "bronze",
    threshold: 1,
    counter: "questionUpvotes",
  },
  silverNiceQuestion: {
    key: "silverNiceQuestion",
    name: "Nice Question II",
    tier: "silver",
    threshold: 10,
    counter: "questionUpvotes",
  },
  goldNiceQuestion: {
    key: "goldNiceQuestion",
    name: "Nice Question III",
    tier: "gold",
    threshold: 50,
    counter: "questionUpvotes",
  },
  bountyHunter: {
    key: "bountyHunter",
    name: "Bounty Hunter",
    tier: "bronze",
    threshold: 1,
    counter: "bountiesWon",
  },
  silverBountyHunter: {
    key: "silverBountyHunter",
    name: "Bounty Hunter II",
    tier: "silver",
    threshold: 5,
    counter: "bountiesWon",
  },
  goldBountyHunter: {
    key: "goldBountyHunter",
    name: "Bounty Hunter III",
    tier: "gold",
    threshold: 25,
    counter: "bountiesWon",
  },
  reputation: {
    key: "reputation",
    name: "Reputation",
    tier: "bronze",
    threshold: 500,
    counter: "reputation",
  },
  silverReputation: {
    key: "silverReputation",
    name: "Reputation II",
    tier: "silver",
    threshold: 2000,
    counter: "reputation",
  },
  goldReputation: {
    key: "goldReputation",
    name: "Reputation III",
    tier: "gold",
    threshold: 5000,
    counter: "reputation",
  },
};
